# 服务器相关
server:
  port: 8861

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blogday
    driver-class-name: com.mysql.jdbc.Driver
    #oracle
#   driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#    username: scott
#    password: root
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #jpa
  application:
    name: provider-student-8861
    #redis
  redis:
    host: localhost
    port: 6379
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: redis
  #邮件
  mail:
    host: smtp.qq.com
    password: jkixhgzdowurbfch
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    username: 895730306@qq.com
  #消息中间件
  activemq:
    #ActiveMQ代理的URL。默认情况下自动生成。
    broker-url: tcp://127.0.0.1:61616
    #是否信任所有包
    packages:
      trust-all: true
  #jpa
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        show-sql: true
# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bwie.entity
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
